#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@bypass2ray[-1]
	add ucitrack bypass2ray
	set ucitrack.@bypass2ray[-1].init=bypass2ray
	commit ucitrack
EOF

uci -q batch <<-EOF >/dev/null
	set firewall.bypass2ray=include
	set firewall.bypass2ray.path='/usr/share/bypass2ray/fw_reload'
EOF

[ ! -s "/etc/config/bypass2ray" ] && cp -f /usr/share/bypass2ray/default_config /etc/config/bypass2ray
chmod 0755 /etc/init.d/bypass2ray
chmod 0755 /usr/share/bypass2ray/*.sh
chmod 0755 /usr/share/bypass2ray/*.lua
passwdfile="/etc/passwd"
name="bypass2ray"
gid="1010"
line="$name:x::$gid:::"
if [ "$(cat $passwdfile | cut -d':' -f1 | grep $name)" = "" ]; then
	echo $line >>$passwdfile
else
	sed -i '/'$name'/s/.*/'$line'/g' $passwdfile
fi
rm -f /tmp/luci-indexcache
rm -rf /tmp/luci-modulecache/
